version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
exclude_patterns:
 - "page_loader/scripts/*.py"
 - "page_loader/__init__.py"
